homepage:
    pattern: /index.{_format}
    defaults:
        _controller: 'OpenWinesWebAppBundle:Default:index'
        _format: html
    requirements:
        _method: GET
        _format: html|json|xml

vignobles:
    pattern: /vignobles.{_format}
    defaults:
        _controller: 'OpenWinesWebAppBundle:Default:vignobles'
        _format: html
    requirements:
        _method: GET
        _format: html|json|xml

vignoble:
    pattern: /vignobles/{id}.{_format}
    defaults:
        _controller: 'OpenWinesWebAppBundle:Default:vignoble'
        _format: html
    requirements:
        _method: GET
        _format: html|json|xml
        id: \d+

appellations:
    pattern: /vignobles/{vignobleId}/appellations.{_format}
    defaults:
        _controller: 'OpenWinesWebAppBundle:Default:appellations'
        _format: html
    requirements:
        _method: GET
        _format: html|json|xml
        vignobleId: \d+

appellation:
    pattern: /vignobles/{vignobleId}/appellations/{id}.{_format}
    defaults:
        _controller: 'OpenWinesWebAppBundle:Default:appellation'
        _format: html
    requirements:
        _method: GET
        _format: html|json|xml
        vignobleId: \d+
        id: \d+

cepages:
    pattern: /vignobles/{vignobleId}/appellations/{AppellationId}/cepages.{_format}
    defaults:
        _controller: 'OpenWinesWebAppBundle:Default:cepages'
        _format: html
    requirements:
        _method: GET
        _format: html|json|xml
        vignobleId: \d+
        AppellationId: \d+

cepage:
    pattern: /vignobles/{vignobleId}/appellations/{AppellationId}/cepages/{id}.{_format}
    defaults:
        _controller: 'OpenWinesWebAppBundle:Default:cepage'
        _format: html
    requirements:
        _method: GET
        _format: html|json|xml
        vignobleId: \d+
        AppellationId: \d+
        id: \d+
