homepage:
    pattern: /index.{_format}
    defaults:
        _controller: 'OpenWinesWebAppBundle:Default:index'
        _format: html
    requirements:
        _method: GET
        _format: html|json|xml

regions:
    pattern: /regions.{_format}
    defaults:
        _controller: 'OpenWinesWebAppBundle:Default:regions'
        _format: html
    requirements:
        _method: GET
        _format: html|json|xml

region:
    pattern: /regions/{id}.{_format}
    defaults:
        _controller: 'OpenWinesWebAppBundle:Default:region'
        _format: html
    requirements:
        _method: GET
        _format: html|json|xml
        id: \d+

Aocs:
    pattern: /regions/{regionId}/aocs.{_format}
    defaults:
        _controller: 'OpenWinesWebAppBundle:Default:Aocs'
        _format: html
    requirements:
        _method: GET
        _format: html|json|xml
        regionId: \d+

Aoc:
    pattern: /regions/{regionId}/aocs/{id}.{_format}
    defaults:
        _controller: 'OpenWinesWebAppBundle:Default:Aoc'
        _format: html
    requirements:
        _method: GET
        _format: html|json|xml
        regionId: \d+
        id: \d+
