open_wines_web_app_homepage:
    pattern: /index.{_format}
    defaults:
        _controller: 'OpenWinesWebAppBundle:Default:index'
        _format: html
    requirements:
        _method: GET
        _format: html|json|xml

open_wines_web_app_regions:
    pattern: /regions.{_format}
    defaults:
        _controller: 'OpenWinesWebAppBundle:Default:regions'
        _format: html
    requirements:
        _method: GET
        _format: html|json|xml

open_wines_web_app_region:
    pattern: /regions/{id}.{_format}
    defaults:
        _controller: 'OpenWinesWebAppBundle:Default:region'
        _format: html
    requirements:
        _method: GET
        _format: html|json|xml
        id: \d+
