homepage:
    pattern: /index.{_format}
    defaults:
        _controller: 'OpenWinesWebAppBundle:Default:index'
        _format: html
    requirements:
        _method: GET
        _format: html|json|xml

vineyards:
    pattern: /vineyards.{_format}
    defaults:
        _controller: 'OpenWinesWebAppBundle:Default:vineyards'
        _format: html
    requirements:
        _method: GET
        _format: html|json|xml

vineyard:
    pattern: /vineyards/{id}.{_format}
    defaults:
        _controller: 'OpenWinesWebAppBundle:Default:vineyard'
        _format: html
    requirements:
        _method: GET
        _format: html|json|xml
        id: \d+

aocs:
    pattern: /vineyards/{vineyardId}/aocs.{_format}
    defaults:
        _controller: 'OpenWinesWebAppBundle:Default:aocs'
        _format: html
    requirements:
        _method: GET
        _format: html|json|xml
        vineyardId: \d+

aoc:
    pattern: /vineyards/{vineyardId}/aocs/{id}.{_format}
    defaults:
        _controller: 'OpenWinesWebAppBundle:Default:aoc'
        _format: html
    requirements:
        _method: GET
        _format: html|json|xml
        vineyardId: \d+
        id: \d+

cepages:
    pattern: /vineyards/{vineyardId}/aocs/{AOCId}/cepages.{_format}
    defaults:
        _controller: 'OpenWinesWebAppBundle:Default:cepages'
        _format: html
    requirements:
        _method: GET
        _format: html|json|xml
        vineyardId: \d+
        AOCId: \d+

cepage:
    pattern: /vineyards/{vineyardId}/aocs/{AOCid}/cepages/{id}.{_format}
    defaults:
        _controller: 'OpenWinesWebAppBundle:Default:cepage'
        _format: html
    requirements:
        _method: GET
        _format: html|json|xml
        vineyardId: \d+
        AOCId: \d+
        id: \d+
