parameters:
#    open_wines_web_app.example.class: OpenWines\WebAppBundle\Example

services:
#    open_wines_web_app.example:
#        class: %open_wines_web_app.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
